[package]
name = "solitaire_solver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
itertools = "0.14.0"
pathfinding = "4.14.0"
rand = "0.9.2"
rand_pcg = "0.9.0"
thiserror = "2.0.17"
